version: "3.4"

x-common-variables: &common-variables
  MYSQL_ROOT_PASSWORD: crawler
  MYSQL_DATABASE: crawler
  MYSQL_USER: crawler
  MYSQL_PASSWORD: crawler

services:
  db:
    build:
      dockerfile: ./docker/db.dockerfile
      context: .
    container_name: crawler_db
    ports:
      - "3308:3306"
    cap_add:
      - SYS_NICE
    environment: *common-variables
    volumes:
      - crawler:/var/lib/mysql
    command: mysqld --init-file="/tmp/database/install_db.sql"
    
  app:
    build:
      dockerfile: ./docker/crawler.dockerfile
      context: .
    container_name: crawler
    environment: *common-variables
    volumes:
      - ./query_lists/:/app/query_lists
    depends_on:
      - "db"
  
volumes:
  crawler:
    external: true
