version: "3"
services:
  crawler_db:
    build:
      dockerfile: ./docker/db.dockerfile
      context: .
    container_name: crawler_db
    ports:
      - "3308:3306"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=crawler
      - MYSQL_DATABASE=crawler
      - MYSQL_USER=crawler
      - MYSQL_PASSWORD=crawler
    volumes:
      - /mysql:/var/lib/mysql
    
  crawler:
    build:
      dockerfile: ./docker/crawler.dockerfile
      context: .
    container_name: crawler
    volumes:
      - ./logs/:/app/
    depends_on:
      - "crawler_db"
